---
- name: Configure system
  hosts: vps
  vars_files:
    - vars/public.yml
    - vars/vault.yml
  roles:
    - role: system
    - role: firewall
    - role: reverse_proxy
    - role: recipes
    - role: backups
    - role: notifications
    - role: artis3n.tailscale.device
