---
- name: Configure system
  hosts: vps
  vars_files:
    - vars/public.yml
    - vars/vault.yml
  roles:
    - role: system
    - role: firewall
    - role: reverse_proxy
    - role: recipes
    - role: backups
    - role: notifications
  tasks:
    - name: Add podman cleanup job
      become: true
      ansible.builtin.cron:
        name: Cleanup dangling podman extras
        minute: "0"
        hour: "3"
        day: "*"
        month: "*"
        weekday: "0"
        job: podman volume prune -f &> /dev/null && podman image prune -af &> /dev/null
