---
- name: Reload systemd for lldap
  ansible.builtin.systemd:
    daemon_reload: true
  become: true
  changed_when: true
- name: Restart lldap
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
  become: true
  loop: "{{ started_services }}"
