---
- name: Set the hostname
  become: true
  ansible.builtin.hostname:
    name: "{{ domain_name }}"
- name: Set timezone to America/New_York
  become: true
  community.general.timezone:
    name: America/New_York
