---
- name: Set logging
  become: true
  community.general.ufw:
    logging: "off"
  notify:
    - Restart firewall
- name: Limit ssh connections
  become: true
  community.general.ufw:
    rule: limit
    port: ssh
    proto: tcp
  notify:
    - Restart firewall
- name: Disable ssh password auth
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: ^PasswordAuthentication
    line: PasswordAuthentication no
  notify:
    - Restart firewall
- name: Enable firewall
  become: true
  community.general.ufw:
    state: enabled
  notify:
    - Restart firewall
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
