---
- name: Install packages
  ansible.builtin.import_tasks: common/tasks/install_packages.yml
- name: Start services
  ansible.builtin.import_tasks: common/tasks/start_services.yml
# only enable ufw so it doesn't kick us out before tailscale is enabled
- name: Enable services
  ansible.builtin.import_tasks: common/tasks/enable_services.yml
