---
- name: Add system user
  become: true
  ansible.builtin.user:
    name: caddy
    shell: /usr/bin/nologin
    system: true
    create_home: true
    home: /var/lib/caddy
- name: Add caddy binary
  become: true
  ansible.builtin.get_url:
    url: "{{ caddy_url }}"
    dest: /usr/local/bin/caddy_linux_amd64_custom
    mode: "0755"
    group: root
    owner: root
    force: true
  notify: Restart caddy
- name: Caddy systemd unit
  become: true
  notify:
    - Reload systemd for caddy
  ansible.builtin.copy:
    dest: /etc/systemd/system/caddy-custom.service
    group: root
    mode: "0644"
    owner: root
    src: caddy-custom.service
- name: Create caddy config directory
  become: true
  ansible.builtin.file:
    group: root
    mode: "0755"
    owner: root
    path: /etc/caddy
    state: directory
- name: Generate Caddyfile
  become: true
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    group: root
    mode: "0644"
    owner: root
  notify: Restart caddy
- name: Allow http
  become: true
  community.general.ufw:
    rule: allow
    port: 80
    proto: tcp
- name: Allow https
  become: true
  community.general.ufw:
    rule: allow
    port: 443
    proto: tcp
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
